from .fertilizacionSerializer import FertilzacionSerializer
from .fincaSerializer import FincaSerializer
from .loteSerializer import LoteSerializer
from .podaSerializer import PodaSerializer
from .riegoSerializer import RiegoSerializer
from .siembraSerializer import SiembraSerializer
from .userSerializer import UserSerializer
from .cosechaSerializer import CosechaSerializer
from .despulpadoSerializer import DespulpadoSerializer
from .fermentacionSerializer import FermentacionSerializer
from .lavadoSerializer import LavadoSerializer
from .maquinaSerializer import MaquinaSerializer
from .moliendaSerializer import MoliendaSerializer
from .secadoSerializer import SecadoSerializer
from .seleccionSerializer import SeleccionSerializer