# Generated by Django 4.0.4 on 2022-10-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha',
            field=models.DateField(verbose_name='FechaNacimiento'),
        ),
    ]
