from .User.userLoginView import UserLoginView
from .User.userCreateView import UserCreateView
from .User.userDetailView import UserDetailView
from .User.userListView import UserListView
from .User.userUpdateView import UserUpdateView
from .User.userDownloadView import UserDownloadView
from .User.userDeleteView import UserDeleteView
from .Finca.fincaCreateView import FincaCreateView
from .Finca.fincaDetailView import FincaDetailView
from .Finca.fincaUpdateView import FincaUpdateView
from .Finca.fincaDeleteView import FincaDeleteView
from .Finca.fincaDownloadView import FincaDownloadView
from .Finca.fincaAllView import FincaAllView
from .Siembra.siembraCreateView import SiembraCreateView
from .Siembra.siembraByLote import SiembraByLoteView
from .Siembra.siembraUpdateView import SiembraUpdateView
from .Siembra.siembraDeleteView import SiembraDeleteView
from .Siembra.siembraDownloadView import SiembraDownloadView
from .Lote.loteCreateView import LoteCreateView
from .Lote.loteDetailView import LoteDetailView
from .Lote.loteAllByFincaView import LoteAllByFincaView
from .Lote.loteUpdateView import LoteUpdateView
from .Lote.loteDeleteView import LoteDeleteView
from .Lote.loteDownloadView import LoteDownloadView
from .Riego.riegoCreateView import RiegoCreateView
from .Riego.riegoDetailView import RiegoDetailView
from .Riego.riegoUpdateView import RiegoUpdateView
from .Riego.riegoDeleteView import RiegoDeleteView
from .Riego.riegoByLoteView import RiegoByLoteView
from .Riego.riegoDownloadView import RiegoDownloadView
from .Poda.podaCreateView import PodaCreateView
from .Poda.podaDetailView import PodaDetailView
from .Poda.podaUpdateView import PodaUpdateView
from .Poda.podaDeleteView import PodaDeleteView
from .Poda.podaByLoteView import PodaByLoteView
from .Poda.podaDownloadView import PodaDownloadView
from .Fertilizacion.fertilizacionCreateView import FertilizacionCreateView
from .Fertilizacion.fertilizacionByLoteView import FertilizacionByLoteView
from .Fertilizacion.fertilizacionUpdateView import FertilizacionUpdateView
from .Fertilizacion.fertilizacionDeleteView import FertilizacionDeleteView
from .Fertilizacion.fertilizacionDownloadView import FertilizacionDownloadView
from .Cosecha.cosechaCreateView import CosechaCreateView
from .Cosecha.cosechaByLoteView import CosechaByLoteView
from .Cosecha.cosechaUpdateView import CosechaUpdateView
from .Cosecha.cosechaDeleteView import CosechaDeleteView
from .Cosecha.cosechaDeleteView import CosechaDeleteView
from .Cosecha.cosechaDownloadView import CosechaDownloadView
from .Despulpado.despulpadoCreateView import DespulpadoCreateView
from .Despulpado.despulpadoByLoteView import DespulpadoByLoteView
from .Despulpado.despulpadoUpdateView import DespulpadoUpdateView
from .Despulpado.despulpadoDeleteView import DespulpadoDeleteView
from .Despulpado.despulpadoDownloadView import DespulpadoDownloadView
from .Fermentacion.fermentacionCreateView import FermentacionCreateView
from .Fermentacion.fermentacionByLoteView import FermentacionByLoteView
from .Fermentacion.fermentacionUpdateView import FermentacionUpdateView
from .Fermentacion.fermentacionDeleteView import FermentacionDeleteView
from .Fermentacion.fermentacionDownloadView import FermentacionDownloadView
from .Lavado.lavadoCreateView import LavadoCreateView
from .Lavado.lavadoByLoteView import LavadoByLoteView
from .Lavado.lavadoUpdateView import LavadoUpdateView
from .Lavado.lavadoDeleteView import LavadoDeleteView
from .Lavado.lavadoDownloadView import LavadoDownloadView
from .Maquina.maquinaCreateView import MaquinaCreateView
from .Maquina.maquinaDetailView import MaquinaDetailView
from .Maquina.maquinaUpdateView import MaquinaUpdateView
from .Maquina.maquinaDeleteView import MaquinaDeleteView
from .Maquina.maquinaAllView import MaquinaAllView
from .Maquina.maquinaDownloadView import MaquinaDownloadView
from .Molienda.moliendaCreateView import MoliendaCreateView
from .Molienda.moliendaByLoteView import MoliendaByLoteView
from .Molienda.moliendaUpdateView import MoliendaUpdateView
from .Molienda.moliendaDeleteView import MoliendaDeleteView
from .Molienda.moliendaDownloadView import MoliendaDownloadView
from .Secado.secadoCreateView import SecadoCreateView
from .Secado.secadoByLoteView import SecadoByLoteView
from .Secado.secadoUpdateView import SecadoUpdateView
from .Secado.secadoDeleteView import SecadoDeleteView
from .Secado.secadoDownloadView import SecadoDownloadView
from .Seleccion.seleccionCreateView import SeleccionCreateView
from .Seleccion.seleccionByLoteView import SeleccionByLoteView
from .Seleccion.seleccionUpdateView import SeleccionUpdateView
from .Seleccion.seleccionDeleteView import SeleccionDeleteView
from .Seleccion.seleccionDownloadView import SeleccionDownloadView
from .Tostion.tostionCreateView import TostionCreateView
from .Tostion.tostionByLoteView import TostionByLoteView
from .Tostion.tostionUpdateView import TostionUpdateView
from .Tostion.tostionDeleteView import TostionDeleteView
from .Tostion.tostionDownloadView import TostionDownloadView
from .Catacion.catacionByLoteView import CatacionByLoteView
from .Catacion.catacionCreateView import CatacionCreateView
from .Catacion.catacionUpdateView import CatacionUpdateView
from .Catacion.catacionDeleteView import CatacionDeleteView
from .Catacion.catacionDownloadView import CatacionDownloadView
